BLS aggregation of 2 signers
stackrlabs/succinct-residency-exps pull request #58
Opened 2024-10-11 23:03 UTC by 0xRampey

fixes https://github.com/stackrlabs/succinct-residency-exps/issues/50

2024-10-12 00:25 UTC, 0xRampey commented
`native_jolt` and `wasm_jolt` are OOMing
Need to increase image size and try again with Delphinus

2024-10-12 00:46 UTC, aashutoshrathi requested changes
rest LGTM

2024-10-12 00:46 UTC, aashutoshrathi commented on bls-agg/rust/wasm/src/lib.rs
> +        let messages: Vec<Vec<u8>> = (0..num_signers)
let's just generate one message and sign it from all

2024-10-15 05:37 UTC, aashutoshrathi requested changes

2024-10-15 05:37 UTC, aashutoshrathi commented on bls-agg/rust/wasm_sp1/script/src/main.rs
> +        .expect("saving proof failed");
```suggestion
        let proof_bytes = proof.bytes();
        println!("Proof Size: {}", proof_bytes.len());
```

2024-10-15 05:37 UTC, aashutoshrathi commented on bls-agg/rust/wasm_risc_zero/host/src/main.rs
> +use methods::{GUEST_CODE_FOR_MERKEL_TREE_ELF, GUEST_CODE_FOR_MERKEL_TREE_ID};
nit: let's change these vars

2024-10-15 05:37 UTC, aashutoshrathi commented on bls-agg/rust/native_sp1/script/src/main.rs
> +        .expect("saving proof failed");
let's just do
```suggestion
        let proof_bytes = proof.bytes();
        println!("Proof Size: {}", proof_bytes.len());
```

2024-10-15 05:37 UTC, aashutoshrathi commented on bls-agg/rust/native_risc_zero/host/src/main.rs
> +use methods::{GUEST_CODE_FOR_MERKELIZATION_ELF, GUEST_CODE_FOR_MERKELIZATION_ID};
nit: change the vars

2024-10-15 06:17 UTC, aashutoshrathi approved these changes

2024-10-15 06:17 UTC, merged